# Generated by Django 5.1.5 on 2025-03-10 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0016_alter_verificator_date_alter_verificator_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificator',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 15, 11, 43, 293316)),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 10, 15, 11, 43, 293334)),
        ),
    ]
