# Generated by Django 5.1.5 on 2025-03-10 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0018_alter_verificator_date_alter_verificator_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_position_tag',
            name='owner_name',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=50),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 15, 23, 25, 388883)),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 10, 15, 23, 25, 388900)),
        ),
    ]
