# Generated by Django 5.1.5 on 2025-03-10 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0020_alter_sport_position_tag_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport_position_tag',
            name='owner_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 15, 27, 52, 57818)),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 3, 10, 15, 27, 52, 57834)),
        ),
    ]
