# Generated by Django 4.2.4 on 2024-03-24 19:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TeamedUp', '0063_alter_open_position_for_un_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unverified_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificator_counter', models.IntegerField(default=0)),
                ('email_flag', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verificator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('time', models.TimeField(default=datetime.datetime(2024, 3, 24, 19, 5, 29, 967625))),
                ('owner', models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='TeamedUp.unverified_profile', unique=0)),
            ],
        ),
    ]
