# Generated by Django 4.2.4 on 2024-03-24 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0064_unverified_profile_verificator'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverified_profile',
            name='code',
            field=models.IntegerField(default='7700522'),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 24, 20, 6, 16, 40896)),
        ),
    ]
