# Generated by Django 4.2.4 on 2024-03-24 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0065_unverified_profile_code_alter_verificator_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverified_profile',
            name='code',
        ),
        migrations.AlterField(
            model_name='verificator',
            name='code',
            field=models.IntegerField(default='2957871'),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 24, 20, 10, 6, 633983)),
        ),
    ]
