# Generated by Django 4.2.4 on 2024-03-24 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0066_remove_unverified_profile_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificator',
            name='code',
            field=models.IntegerField(default='9499997'),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.DateField(default=datetime.datetime(2024, 3, 24, 20, 16, 14, 350247)),
        ),
    ]
