# Generated by Django 4.2.4 on 2024-03-24 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0067_alter_verificator_code_alter_verificator_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificator',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 24, 20, 18, 36, 396622)),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='code',
            field=models.IntegerField(default='2572114'),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 24, 20, 18, 36, 396715)),
        ),
    ]
