# Generated by Django 4.2.4 on 2024-03-25 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0068_verificator_date_alter_verificator_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificator',
            name='verificator_page_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 25, 10, 57, 34, 497001)),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 25, 10, 57, 34, 497077)),
        ),
    ]
