# Generated by Django 4.2.4 on 2024-03-30 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0073_alter_verificator_code_alter_verificator_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificator',
            name='code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 30, 10, 34, 12, 133736)),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 30, 10, 34, 12, 133813)),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='verificator_page_id',
            field=models.CharField(default=0, max_length=14),
        ),
    ]
