# Generated by Django 4.2.4 on 2024-03-30 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamedUp', '0074_alter_verificator_code_alter_verificator_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificator',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 30, 10, 44, 9, 691616)),
        ),
        migrations.AlterField(
            model_name='verificator',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 30, 10, 44, 9, 691633)),
        ),
    ]
